#!/bin/bash

FILEDIR=~/Downloads
OPTION=()

values=$(zenity \
  --title=wayland-screenshot \
  --text="Option" \
  --forms \
  --add-combo="Mode" \
    --combo-values="All screen|Specific window|Specific area" \
  --add-combo="Include cursor[default: no]" \
    --combo-values="no|yes" \
    --add-entry="time to wait[default: 0s]")

result=$?

mode=$(echo $values | cut -d '|' -f 1)
cursor=$(echo $values | cut -d '|' -f 2)
wait=$(echo $values | cut -d '|' -f 3)

if [ "$result" -eq 1 ];then      # select cancel
	echo "canceling"
	exit
fi

if [ ! -z "$cursor" ] &&  [ "$cursor" == yes ];then
	OPTION+="-c"
fi

if [ -z "$mode" ] ;then       # select nothing
	echo "mode is null"
	zenity \
		--title=wayland-screenshot \
		--width=200 \
		--warning \
		--text="Mode empty"
	exit
fi

if [ ! -z "$wait" ];then
	sleep $wait
fi

if [ "$mode" == "All screen" ];then  # select All screen
	grim $OPTION $FILEDIR/Screenshot_$(date +%F_%T).png
elif [ "$mode" == "Specific window" ];then  # select specify window
	grim -g "$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp)" $OPTION $FILEDIR/Screenshot_$(date +%F_%T).png
elif [ "$mode" == "Specific area" ];then  # select specfy area
	grim -g "$(slurp)" $OPTION $FILEDIR/Screenshot_$(date +%F_%T).png
else                         # error
	echo $mode
fi
